// JP lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- スタイル --',
theme_code_desc : 'ソースの直接編集',
theme_code_title : 'HTMLソース',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : '上添字',
theme_sup_desc : '下添字',
theme_hr_desc : '水平線挿入',
theme_removeformat_desc : '整形破棄',
theme_custom1_desc : 'Your custom description here',
insert_image_border : '囲み線',
insert_image_dimensions : '画像角度',
insert_image_vspace : '上下余白',
insert_image_hspace : '左右余白',
insert_image_align : 'Align',
insert_image_align_default : '-- 未定義 --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Top',
insert_image_align_middle : 'Middle',
insert_image_align_bottom : 'Bottom',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Left',
insert_image_align_right : 'Right',
theme_font_size : '-- フォントサイズ --',
theme_fontdefault : '-- フォント --',
theme_block : '-- 段落スタイル --',
theme_paragraph : 'P',
theme_div : 'Div',
theme_address : 'Address',
theme_pre : 'Pre',
theme_h1 : 'H1',
theme_h2 : 'H2',
theme_h3 : 'H3',
theme_h4 : 'H4',
theme_h5 : 'H5',
theme_h6 : 'H6',
theme_colorpicker_title : '色の選択',
theme_colorpicker_apply : '適用',
theme_forecolor_desc : 'テキスト色選択',
theme_backcolor_desc : '背景色選択',
theme_charmap_title : '特殊文字の挿入',
theme_charmap_desc : '特殊文字の挿入',
theme_visualaid_desc : '表示/非表示の切替',
insert_anchor_title : 'アンカーの挿入/編集',
insert_anchor_name : 'アンカー名',
theme_anchor_desc : 'アンカーの挿入/編集',
theme_insert_link_titlefield : 'Title',
theme_clipboard_msg : 'Mozilla/Firefoxでは切取り、コピー、貼付けはできません',
theme_path : 'パス',
cut_desc : '切取り',
copy_desc : 'コピー',
paste_desc : '貼付け',
link_list : 'リンク一覧',
image_list : '画像一覧',
browse : 'ブラウズ',
image_props_desc : '画像のプロパティ',
newdocument_desc : '新規ドキュメント',
class_name : 'クラス',
newdocument : 'すべて消去してよろしいですか?',
about_title : 'About TinyMCE',
about : 'About',
license : 'ライセンス',
plugins : 'プラグイン',
plugin : 'プラグイン',
author : 'Author',
version : 'バージョン',
loaded_plugins : 'Loaded plugins',
help : 'ヘルプ',
not_set : '-- 未選択 --',
close : '閉じる',
toolbar_focus : 'Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X'
});
