<meta http-equiv="Content-Type" content="text/html; charset=<%charset%>" />
<title><%conf(SiteName)%> - Admin</title>
<base href="<%self%>" />

<link rel="stylesheet" title="Nucleus Admin Default" type="text/css" href="<%skinfile(styles/admin.css)%>" />
<link rel="stylesheet" title="Nucleus Admin Default" type="text/css" href="<%skinfile(styles/addedit.css)%>" />

<script type="text/javascript" src="<%skinfile(javascript/edit.js)%>"></script>
<script type="text/javascript" src="<%skinfile(javascript/admin.js)%>"></script>
<script type="text/javascript" src="<%skinfile(javascript/compatibility.js)%>"></script>

<meta http-equiv='Pragma' content='no-cache' />
<meta http-equiv='Cache-Control' content='no-cache, must-revalidate' />
<meta http-equiv='Expires' content='-1' />
