// UK lang variables

tinyMCE.addToLang('table',{
general_tab : '基本',
advanced_tab : '詳細',
general_props : '基本設定',
advanced_props : '詳細設定',
desc : '表の挿入',
row_before_desc : '行挿入(前)',
row_after_desc : '行挿入(後)',
delete_row_desc : '行削除',
col_before_desc : '列挿入(前)',
col_after_desc : '列挿入(後)',
delete_col_desc : '列削除',
rowtype : 'Row in table part',
title : 'Insert/Modify table',
width : '幅',
height : '高さ',
cols : '列',
rows : '行',
cellspacing : 'セル間の余白',
cellpadding : 'セル内の余白',
border : '罫線',
align : '揃え位置',
align_default : '未指定',
align_left : '左',
align_right : '右',
align_middle : '中央',
row_title : '行のプロパティ',
cell_title : 'セルのプロパティs',
cell_type : 'セルの種類',
row_desc : '行のプロパティ',
cell_desc : 'セルのプロパティ',
valign : '縦揃え位置',
align_top : 'Top',
align_bottom : 'Bottom',
props_desc : '表のプロパティ',
bordercolor : '罫線の色',
bgcolor : '背景色',
merge_cells_title : 'セルの結合',
split_cells_desc : 'セルの分割',
merge_cells_desc : 'セルを結合する',
cut_row_desc : '行の切取り',
copy_row_desc : '行のコピー',
paste_row_before_desc : '行の貼付け(前へ)',
paste_row_after_desc : '行の貼付け(後ろへ)',
id : 'Id',
style: 'スタイル',
langdir : 'Language direction',
langcode : 'Language code',
mime : 'Target MIME type',
ltr : 'Left to right',
rtl : 'Right to left',
bgimage : '背景の画像',
summary : 'Summary',
td : "Data",
th : "Header",
cell_cell : '現在のセルにセットする',
cell_row : 'この行のセルにセットする',
cell_all : '表内のすべてのセルにセットする',
row_row : '現在の行を上書き',
row_odd : '奇数行のセルを上書き',
row_even : '偶数行のセルを上書き',
row_all : '表内のすべてのセルを上書き',
thead : 'Table Head',
tbody : 'Table Body',
tfoot : 'Table Foot',
del : '表を削除',
scope : 'Scope',
row : '行',
col : '列',
rowgroup : 'グループ行',
colgroup : 'グループ列',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});
