<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <th class="thHead">よくある質問</th>
  </tr>
  <tr>
    <td class="row1">
      <span class="gen"><b>ログインと登録に関する問題</b></span><br>

      <span class="gen"><a href="#0" class="postlink">何故ログインできないのでしょうか？</a></span><br>
      <span class="gen"><a href="#1" class="postlink">登録は必ずしなければいけないですか？</a></span><br>
      <span class="gen"><a href="#2" class="postlink">何故自動的にログオフしてしまうのでしょうか？</a></span><br>
      <span class="gen"><a href="#3" class="postlink">オンライン状態のユーザーとして名前をリストに表示されないようにするにはどうすればいいのでしょうか？</a></span><br>
      <span class="gen"><a href="#4" class="postlink">パスワードが無くなってしまいました。</a></span><br>
      <span class="gen"><a href="#5" class="postlink">登録したのにログインすることができません。</a></span><br>

      <span class="gen"><a href="#6" class="postlink">過去に登録したのにログインできません。</a></span><br>
      <br>
      <span class="gen"><b>ユーザー設定</b></span><br>
      <span class="gen"><a href="#7" class="postlink">どのようにユーザー設定を変更できますか？</a></span><br>
      <span class="gen"><a href="#8" class="postlink">時刻が正しくありません。</a></span><br>
      <span class="gen"><a href="#9" class="postlink">タイムゾーン設定を変更しても時刻が正しくありません。</a></span><br>

      <span class="gen"><a href="#10" class="postlink">掲示板の言語に私の使用する言語がありません。</a></span><br>
      <span class="gen"><a href="#11" class="postlink">どのように名前の下に画像を表示できますか？</a></span><br>
      <span class="gen"><a href="#12" class="postlink">どのようにランクを変更できますか？</a></span><br>
      <span class="gen"><a href="#13" class="postlink">メールアイコンを使ってユーザーにメールを送信しようとするとログイン画面が表示されます。</a></span><br>
      <br>
      <span class="gen"><b>投稿に関する問題</b></span><br>

      <span class="gen"><a href="#14" class="postlink">どのようにトピックを投稿できますか？</a></span><br>
      <span class="gen"><a href="#15" class="postlink">どのように記事を削除/編集できますか？</a></span><br>
      <span class="gen"><a href="#16" class="postlink">どのように自分の記事にサインを追加できますか？</a></span><br>
      <span class="gen"><a href="#17" class="postlink">どのように記事に投票を追加できますか？</a></span><br>
      <span class="gen"><a href="#18" class="postlink">どのように投票の削除/編集を行うことができますか？</a></span><br>
      <span class="gen"><a href="#19" class="postlink">何故フォーラムにアクセスできないのでしょうか？</a></span><br>

      <span class="gen"><a href="#20" class="postlink">何故投票が行えないのでしょうか？</a></span><br>
      <br>
      <span class="gen"><b>フォーマットとトピックの種類</b></span><br>
      <span class="gen"><a href="#21" class="postlink">BBCodeとは何でしょうか？</a></span><br>
      <span class="gen"><a href="#22" class="postlink">HTMLを使うことはできますか？</a></span><br>
      <span class="gen"><a href="#23" class="postlink">スマイリーとは何でしょうか？</a></span><br>

      <span class="gen"><a href="#24" class="postlink">記事の本文中に画像を載せることはできますか？</a></span><br>
      <span class="gen"><a href="#25" class="postlink">重要トピックとは何でしょうか？</a></span><br>
      <span class="gen"><a href="#26" class="postlink">告知トピックとは何でしょうか？</a></span><br>
      <span class="gen"><a href="#27" class="postlink">ロックトピックとは何でしょうか？</a></span><br>
      <br>
      <span class="gen"><b>ユーザーレベルとグループ</b></span><br>

      <span class="gen"><a href="#28" class="postlink">管理者とは何でしょうか？</a></span><br>
      <span class="gen"><a href="#29" class="postlink">モデレーターとは何でしょうか？</a></span><br>
      <span class="gen"><a href="#30" class="postlink">ユーザーグループとは何でしょうか？</a></span><br>
      <span class="gen"><a href="#31" class="postlink">どのようにグループに参加することができますか？</a></span><br>
      <span class="gen"><a href="#32" class="postlink">どのようにグループのモデレーターになることができますか？</a></span><br>
      <br>

      <span class="gen"><b>PM（プライベートメッセージ）</b></span><br>
      <span class="gen"><a href="#33" class="postlink">プライベートメッセージを送信できません。</a></span><br>
      <span class="gen"><a href="#34" class="postlink">読みたくないPMを定期的に受信しています。</a></span><br>
      <span class="gen"><a href="#35" class="postlink">この掲示板のユーザーによって、スパム等が自分のメールアドレスに送信されています。</a></span><br>
      <br>
      <span class="gen"><b>phpBB 2関連の情報</b></span><br>

      <span class="gen"><a href="#36" class="postlink">phpBB 2を作成したのは誰でしょうか？</a></span><br>
      <span class="gen"><a href="#37" class="postlink">必要な機能がありません。</a></span><br>
      <span class="gen"><a href="#38" class="postlink">この掲示板に関連した不正・法的問題については誰に問い合わせればいいのでしょうか？</a></span><br>
      <br>
    </td>
  </tr>
  <tr>

    <td class="catBottom" height="28">&nbsp;</td>
  </tr>
</tbody></table>
