<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">ログインと登録に関する問題</span></td>
  </tr>
  <tr>

    <td class="row1" align="left" valign="top"><span class="postbody"><a name="0"></a><b>何故ログインできないのでしょうか？</b></span><br><span class="postbody">ユーザー登録は行いましたか？ログインするためにはユーザー登録を行う必要があります。あるいは掲示板の使用を禁止されていますか（禁止されている場合は画面に禁止されていると表示されます）？ 使用を禁止されている場合は、管理者に何故禁止されたのかを問い合わせる必要があります。上記のことが原因でないにも関わらずログインができない場合は、ログイン時の名前とパスワードを確かめてください。通常はこれが問題であることが多いですが、これでもない場合は管理者に問い合わせてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="1"></a><b>登録は必ずしなければいけないですか？</b></span><br><span class="postbody">掲示板の管理方針によっては、ログインしなくても投稿するできる場合がありますので、必ずしも登録する必要はありません。しかし、登録をすることでユーザー画像の使用、プライベートメッセージ（PM）の使用、仲間のユーザーへのメール送信、グループの参加など様々な機能にアクセスすることができるようになります。登録をしていないゲストユーザーの場合は、利用できる機能が登録ユーザーよりも少ないです。登録は数分で行うことができますので、掲示板をよく使う場合はユーザー登録することをお勧めします。<br><a class="postlink" href="#top">トップに移動</a></span></td>

  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="2"></a><b>何故自動的にログオフしてしまうのでしょうか？</b></span><br><span class="postbody">「自動ログインを有効にする」のボックスをチェックしていない場合は、一時的にしかログインしません。 常にログイン状態でありたい場合は、このボックスをチェックしてからログインします。この自動ログイン機能は図書館、インターネット喫茶、大学などの共有されたコンピューター環境では利用しないことをお勧めします。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="3"></a><b>オンライン状態のユーザーとして名前をリストに表示されないようにするにはどうすればいいのでしょうか？</b></span><br><span class="postbody">ユーザー設定にある「オンラインステータスを隠す」を「はい」にすると、あなたのオンライン状態は管理人以外には表示されません。この場合は隠れユーザーとして数えられます。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="4"></a><b>パスワードが無くなってしまいました。</b></span><br><span class="postbody">無くしたパスワードを取り戻すことはできませんが、パスワードを再発行することができます。パスワードを再発行する場合は、ログイン画面に入って「パスワードを忘れてしまいました」を選択し、登録した名前とメールアドレスを入力して送信します。再発行されたパスワードは、入力したメールアドレスに送信されます。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>

  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="5"></a><b>登録したのにログインすることができません。</b></span><br><span class="postbody">まず最初に正しい名前とパスワードを入力しているかを確認してください。両方とも正しい場合は、次の2つが問題である可能性があります。1つ目は、掲示板がCOPPA（子供のオンライン・プライバシー保護法）の設定を有効にしている場合、13歳未満として登録しているユーザーは与えられた指示に従う必要があります。2つ目は、アカウントをアクティブにしたかを確認してください。掲示板の設定によっては、登録したアカウントのアクティベーションを行わないとアカウントが有効になりません。アクティベーションが必要かどうかは登録完了時に知らされます。アクティブ用のメールが送られているはずなので文章の指示に従ってアクティベーションを行ってください。メールが送信されていない場合は、登録時に正しいメールアドレスを入力したかを確認してください。アカウントのアクティベーション機能が使われている理由の一つとして、無作法なユーザーによる匿名性の乱用等を防ぐということが挙げられます。正しいメールアドレスを入力したにも関わらず登録できない場合は、掲示板の管理者に問い合わせてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>

  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="6"></a><b>過去に登録したのにログインできません。</b></span><br><span class="postbody">最も可能性のある理由は、間違った名前とパスワードでログインしようとしているため（登録した時に送信されたメールに載っているアカウントを確認してください）、又は、管理者が何らかの理由であなたのアカウントを削除したためでしょう。後者が当てはまる人は、投稿した経験があるでしょうか？管理者によってはデータベースのサイズを小さくするために、登録してから全く投稿を行わないユーザーのアカウントを削除することがあります。この場合は再び登録をして、積極的に議論に参加しましょう。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
</tbody></table>
