<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">ユーザー設定</span></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="7"></a><b>どのようにユーザー設定を変更できますか？</b></span><br><span class="postbody">全ての設定はデータベースに保管されています。ユーザー設定を変更する場合は、通常ページの上のの部分にあるメニューの「ユーザー設定」をクリックしてください。この画面で全てのユーザー設定を変更することができます。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="8"></a><b>時刻が正しくありません。</b></span><br><span class="postbody">設定しているタイムゾーンによって、時刻が正しく表示されていない場合があります。この場合は、ユーザー設定で時間が合うようにタイムゾーンを設定する必要があります。タイムゾーン等のユーザー設定は登録したユーザーしか行うことができないので注意してください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="9"></a><b>タイムゾーン設定を変更しても時刻が正しくありません。</b></span><br><span class="postbody">正しいタイムゾーン設定を行っても時刻が正しくない場合、その問題のほとんどがサマータイムによるものです。掲示板の時刻システムはサマータイムに対応していないので、正しい時刻を表示させたい場合は、タイムゾーン設定を1時間ずらす必要があります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>

  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="10"></a><b>掲示板の言語に私の使用する言語がありません。</b></span><br><span class="postbody">使用したい言語がない理由は、その言語ファイルが掲示板に導入されていないか、誰も基本言語ファイル（基本言語は英語）をその言語に翻訳していないかのどちらかです。使用したい言語ファイルが存在する場合は、掲示板の管理者に導入してもらいます。もしも使用したい言語ファイルが存在しない場合は、是非とも翻訳して言語ファイルを作ってください。詳細はphpBB Groupのウェブサイトを見てください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>

  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="11"></a><b>どのように名前の下に画像を表示できますか？</b></span><br><span class="postbody">名前の下に表示される画像は2種類あります。一つは投稿数に応じたランクの画像です。もう一つはユーザー画像です。ユーザー画像は一般的に各ユーザーの好きな画像を選択することができます。掲示板の設定によって定められたユーザー画像しか使えなかったり、一切ユーザー画像が使えない場合があります。ユーザー画像を一切使用できない場合は、どうしてユーザー画像が使用できないかを管理者に問い合わせてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>

    <td class="row2" align="left" valign="top"><span class="postbody"><a name="12"></a><b>どのようにランクを変更できますか？</b></span><br><span class="postbody">基本的にランクを変更することはできません。ほとんどの掲示板は、投稿数に応じたランク、管理者やモデレーター等の特定の権限を持つユーザーのみに表示されるランクを使用しています。ランクを上げるために掲示板に無駄な記事を投稿しないようにしてください。場合によっては、ランクを下げられたり、アカウントを削除される可能性があります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="13"></a><b>メールアイコンを使ってユーザーにメールを送信しようとするとログイン画面が表示されます。</b></span><br><span class="postbody">残念ながら掲示板によるメール送信は登録ユーザーしか行うことができません（掲示板によるメール送信機能は掲示板の設定によって無効になっている場合があります）。これは匿名ユーザーによるメールを使った悪質な行為を防ぐためです。<br><a class="postlink" href="#top">トップに移動</a></span></td>

  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
</tbody></table>
