<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">投稿に関する問題</span></td>

  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="14"></a><b>どのようにトピックを投稿できますか？</b></span><br><span class="postbody">新規トピックのボタンをクリックすれば投稿することができます。掲示板の設定によっては、記事を投稿するために登録を行っている必要があります。フォーラム画面とトピック画面の右下に自分ができるアクションが表示されます。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>

  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="15"></a><b>どのように記事を削除/編集できますか？</b></span><br><span class="postbody">一般のユーザーは自分の記事の削除/編集しか行えません。編集を行う場合は、編集したい記事の編集ボタンをクリックします。その記事に返信がある場合は、編集後に記事に編集した回数が表示されます。返信のない記事を編集する場合や、モデレーターと管理者が編集する場合は編集回数は表示されません。削除に関しては、一般のユーザーは返信のある記事を削除することができませんので注意してください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>

    <td class="row1" align="left" valign="top"><span class="postbody"><a name="16"></a><b>どのように自分の記事にサインを追加できますか？</b></span><br><span class="postbody">サインを追加するためにはユーザー設定を行う必要があります。ユーザー設定画面の「サイン」の欄に追加したいサインを入力して設定します。そして投稿画面で「サインを有効にする」をチェックすれば、自分の記事の本文の一番下にサインを追加することができます。ユーザー設定画面の「サインを常に有効にする」を有効にしていれば、投稿画面の「サインを有効にする」は常にチェックされた状態になります（チェックを外せばサインは追加されません）。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="17"></a><b>どのように記事に投票を追加できますか？</b></span><br><span class="postbody">投票を追加する場合は、新規トピックを投稿するときに「投票の追加/編集」の欄を使います。ここで投票のお題と選択肢を最低2つ作ります（選択肢を作るときは「選択肢を追加」をクリックしてください）。投票期間を設けることもできますが、特に期間を設けない場合は0に設定してください。ちなみに選択肢の数は制限されています（数の上限は掲示板の設定によります）。<br><a class="postlink" href="#top">トップに移動</a></span></td>

  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="18"></a><b>どのように投票の削除/編集を行うことができますか？</b></span><br><span class="postbody">投票の削除/編集は投票を作成したユーザー、モデレーター、管理者しか行うことができません。投票の削除/編集は、記事の編集ボタンをクリックし、投票関連の情報の削除/編集を行います。一票でもはいっている投票の編集/削除は行うことができませんので注意してください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="19"></a><b>何故フォーラムにアクセスできないのでしょうか？</b></span><br><span class="postbody">一部のフォーラムは特定のグループやユーザーしか観閲できないように制限がかかっていることがあります。これらのフォーラムを使う権限は、モデレーターと管理人しか与えることができないので、必要に応じて権限を与えてもらうようにしてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="20"></a><b>何故投票が行えないのでしょうか？</b></span><br><span class="postbody">投票の混乱を招くような大量投稿などを防ぐため、登録ユーザーしか投票を行うことはできません。登録ユーザーなのに投票が行えない場合は、適切なアクセス権限が与えられていない可能性があります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>

  </tr>
</tbody></table>
