<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">フォーマットとトピックの種類</span></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="21"></a><b>BBCodeとは何でしょうか？</b></span><br><span class="postbody">BBCodeとは特殊なHTMLの実行コードです。BBCodeの使用は管理者によって設定されていますので、設定でBBCodeが無効となっている場合は使うことができません。BBCodeが有効となっている場合でも、ユーザーは投稿画面でBBCodeを無効にすることができます。BBCodeはHTMLと似たスタイルをしていて、タグは&lt; &gt;ではなく[ ]が用いられます。使用するテンプレートによってBBCodeは記事内容投稿欄の上にBBCode用のボタンがあり、これ使うことで直接BBCodeタグを入力することなく挿入することができます。詳細は投稿画面のオプションにある「BBCode」のリンクをクリックしてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>

  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="22"></a><b>HTMLを使うことはできますか？</b></span><br><span class="postbody">HTMLを使用できるかは掲示板の設定によって異なります。HTMLの使用が許可されている場合でも、全てのHTMLタグを使えるわけではありません。これは一部のHTMLタグを使用することで表示等において問題が生じてしまうのを防ぐ安全策です。HTMLを使用したくない場合は、投稿画面で「HTMLを無効にする」をチェックしてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="23"></a><b>スマイリーとは何でしょうか？</b></span><br><span class="postbody">スマイリー（別称はエモーションアイコン）とは感情を表現するために用いられる小さな画像のことです。例えば、:) は嬉しい感情、:( は悲しい感情を表します。投稿画面にスマイリー一覧が載っています。投稿画面では複数の記号として表示されますが、記事ではスマイリー画像として表示されます。ただし、スマイリーが多くなると記事が読みづらくなりますので、スマイリーの乱用はしないでください。スマイリーを乱用した記事は、編集/削除/移動対象となる可能性があります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="24"></a><b>記事の本文中に画像を載せることはできますか？</b></span><br><span class="postbody">本文中の画像を載せることはできます。しかし、画像を掲示板上にアップロードする機能はありません。そのため、インターネット上に存在する画像を利用する必要があります。サーバーでない限り、自分のコンピューター内にある画像にリンクしても掲示板では表示されません。また、アクセスにパスワード等が必要なサイト内の画像、HotmailやYahooのメールボックス内の画像等も利用できませんので注意してください。画像を表示させるには画像URLを<b>[img][/img]</b>で囲みます（HTMLの使用が許可されている場合はHTMLタグも使用できます）。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="25"></a><b>重要トピックとは何でしょうか？</b></span><br><span class="postbody">重要トピックは、掲示板利用者であればすぐに読むべき重要な情報が載っているトピックです。重要トピックはフォーラムの各ページの一番上に表示されます。重要トピックに返信を行えるかどうかはユーザーの権限によります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>

  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="26"></a><b>告知トピックとは何でしょうか？</b></span><br><span class="postbody">告知トピックとは、最初のページの重要トピックの下（重要トピックがない場合は一番上）に表示されるトピックで、比較的重要な情報が含まれています。そのため、告知トピックは読めるときに読んでください。告知トピックに返信を行えるかどうかはユーザーの権限によります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>

  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="27"></a><b>ロックトピックとは何でしょうか？</b></span><br><span class="postbody">ロックトピックとは返信が禁止されているトピック（投票がある場合は投票も禁止されています）です。様々な理由により、モデレーターや管理者によってトピックがロックされることがあります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
</tbody></table>
