<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">ユーザーレベルとグループ</span></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="28"></a><b>管理者とは何でしょうか？</b></span><br><span class="postbody">管理者とは、掲示板における最高権限を持つ人のことです。管理者は、パーミッション設定、特定のユーザーの掲示板使用の禁止、グループやモデレーターの作成等掲示板における全ての設定と操作を行うことができます。もちろん管理者は、全てのフォーラムにおいて完全なモデレーター権限を持っています。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="29"></a><b>モデレーターとは何でしょうか？</b></span><br><span class="postbody">モデレーターとは、フォーラムの管理を行う人のことです。モデレーターは、他人の記事の削除/編集/ロック/移動等の権限を持っています。基本的にモデレーターの役割とは、フォーラムの趣旨を外れた投稿、規約に反する投稿などを削除等を行うことで、そのフォーラムの秩序を保つことです。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="30"></a><b>ユーザーグループとは何でしょうか？</b></span><br><span class="postbody">ユーザーグループとは、管理者がユーザーをグループ分けする方法の一つです。ユーザーグループはグループと呼ぶこともあります。各ユーザーは複数のグループに所属することができて、各グループには個々のアクセス権限が適用されます。これによって管理者は、複数のモデレーターをグループにいれることで管理することが容易になったり、特定のユーザーしか入れないフォーラムを提供することも容易になります。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>

  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="31"></a><b>どのようにグループに参加することができますか？</b></span><br><span class="postbody">グループに参加する場合は、ページの上の部分にある「グループ」をクリックしてください。グループ画面に入ると、全てのグループが表示されます。全てのグループが誰でも参加できるオープングループとは限らず、特定のユーザーしか受け入れないクローズドグループ、メンバーが一切表示されない隠れグループもあります。オープングループの場合は、正しい手順で参加の申請を行ってください。参加の申請がグループのモデレーターに承認されると、晴れてグループのメンバーとなることができます。場合によっては、グループに参加する理由をグループのモデレーターに問われることもあります。何らかの理由で参加の申請を却下された場合は、グループのモデレーターを問い詰めるようなことはしないでください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>

  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="32"></a><b>どのようにグループのモデレーターになることができますか？</b></span><br><span class="postbody">グループは管理者によって作られるものですが、その際に管理者はグループを管理する人間を任命します。これがグループのモデレーターです。一般的にグループの作成を申請した人がグループのモデレーターとなることが多いようです。新しいグループを作りたい場合は、PM（プライベートメッセージ）等を使って管理者にグループ作成に関して問い合わせてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
</tbody></table>
