<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">PM（プライベートメッセージ）</span></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="33"></a><b>プライベートメッセージを送信できません。</b></span><br><span class="postbody">3つの理由があると考えられます。1つ目は登録ユーザーでないため、（PMは登録ユーザーしか使用できない機能です）。2つ目はその掲示板でPMの使用が許可されていないため、3つ目は管理者があなたのPMの使用を禁止しているためです。3つ目の場合は、管理者に何故PMの使用を禁止されたかを問い合わせてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="34"></a><b>読みたくないPMを定期的に受信しています。</b></span><br><span class="postbody">次期バージョンでは、プライベートメッセージシステムに無視リスト機能を追加する予定です。現在のバージョンの対策は、管理者に報告して対処してもらうしかありません。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="35"></a><b>この掲示板のユーザーによって、スパム等が自分のメールアドレスに送信されています。</b></span><br><span class="postbody">まことに残念な出来事です。掲示板にはセーフガード機能があり、誰が掲示板を介してそのようなメールを送ったかを探知できます。今まで受信したスパム等のメールのコピーを管理者に送信してください。管理者に送信するコピーにはヘッダー情報が含まれていることを確認してください。これにより、管理者はこの問題に対処することができます。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>

  </tr>
</tbody></table>
