<table class="forumline" align="center" border="0" cellpadding="3" cellspacing="1" width="100%">
  <tbody><tr>
    <td class="catHead" align="center" height="28"><span class="cattitle">phpBB 2関連の情報</span></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="36"></a><b>phpBB 2を作成したのは誰でしょうか？</b></span><br><span class="postbody">このソフトウェアは<a href="http://www.phpbb.com/" target="_blank">phpBB Group</a>によって作られたもので、著作権はphpBB Groupが有しています。phpBB 2は、GNU 一般公有使用許諾書に定められている条件に従って使用や配布が許諾されています。詳細については、phpBB Groupのサイトを見てください。<br><a class="postlink" href="#top">トップに移動</a></span></td>

  </tr>
  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row2" align="left" valign="top"><span class="postbody"><a name="37"></a><b>必要な機能がありません。</b></span><br><span class="postbody">このソフトウェアの作成を行ったのはphpBB Groupで、著作権はphpBB Groupが有しています。その機能が必要なものだと思う場合は、phpbb.comのサイトを訪れて、php Groupに提案してみてください。新機能の提案・要望は、決してphpbb.comの掲示板には書き込まないでください。新機能等の追加の作業はsourceforgeで行われています。フォラームをよく読み、既に提案しようとしている新機能の追加が決まっているかを確認してから、新機能の提案・要望の手順を行ってください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>

  <tr>
    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
  <tr>
    <td class="row1" align="left" valign="top"><span class="postbody"><a name="38"></a><b>この掲示板に関連した不正・法的問題については誰に問い合わせればいいのでしょうか？</b></span><br><span class="postbody">この掲示板の管理者に問い合わせてください。管理者が誰か分からない場合は、モデレーターに管理者が誰なのかを尋ねてみてください。モデレーターから応答がない場合は、ドメインの管理者等に問い合わせてください（whois lookupを使って調べてみてください）。phpBB Groupには、誰が何処でどのようにこの掲示板が使用するかに干渉する権限は全くないということに注意してください。phpBB Groupの方に直接phpbb.comやphpBBのソフトウェアと関わりのない法的問題に関連することを問い合わせても無意味です。第三者によるphpBBの使用に関してphpBB Groupにメールで問い合わせても、回答は簡単なものか全くされないものと考えてください。<br><a class="postlink" href="#top">トップに移動</a></span></td>
  </tr>
  <tr>

    <td class="spaceRow" height="1"><img src="templates/subSilver/images/spacer.gif" alt="" height="1" width="1"></td>
  </tr>
</tbody></table>
