<table width="100%" cellspacing="0" cellpadding="2" border="0" align="center">
  <tr>
  <td align="left" valign="bottom"><span class="gensmall">
    現在の時刻 - <%subSilver(showClock,subSilver/index)%><br /></span><span class="nav"><a href="<%sitevar(url)%>" class="nav"><%sitevar(name)%> フォーラム一覧</a></span>
  </td>
  </tr>
</table>

<%subSilver(includelanguage,faq.inc)%><br />
<%subSilver(includelanguage,faq1.inc)%><br />
<%subSilver(includelanguage,faq2.inc)%><br />
<%subSilver(includelanguage,faq3.inc)%><br />
<%subSilver(includelanguage,faq4.inc)%><br />
<%subSilver(includelanguage,faq5.inc)%><br />
<%subSilver(includelanguage,faq6.inc)%><br />
<%subSilver(includelanguage,faq7.inc)%><br />
