<table align="center" border="0" cellpadding="2" cellspacing="2" width="100%">
	<tbody><tr>
		<td align="left"><span class="nav"><a href="<%sitevar(url)%>" class="nav"><%sitevar(name)%> フォーラム一覧</a>
		-&gt; <a class="nav" href="<%self%>?blogid=<%blogsetting(id)%>&amp;catid=<%category(id)%>"><%category(name)%></a></span></td></span></td>
	</tr>
</tbody></table>

<table class="forumline" border="0" cellpadding="3" cellspacing="1" width="100%">

	<tbody><tr>
		<th class="thHead" colspan="2" height="25"><b>トピックの新規投稿</b></th>
	</tr>
	<tr>
      <td  class="commentform">
        <table align="center" border="0"><tr><td>
          <%subSilver(commentform)%>
        </td></tr></table>
      </td>
	</tr>
  </tbody>
</table>
