<table align="center" border="0" cellpadding="2" cellspacing="2" width="100%">
<tbody><tr>
  <td align="left"><span class="nav"><a class="nav" href="<%sitevar(url)%>"><%sitevar(name)%> フォーラム一覧</a></span></td>
</tr>
</tbody></table>

<table class="forumline" border="0" cellpadding="3" cellspacing="1" width="100%">
<tbody><tr>
  <th class="thHead" height="25" valign="middle"><%sitevar(name)%> - 登録規約</th>
</tr>
<tr>
  <td class="row1" align="center"><table align="center" border="0" cellpadding="2" cellspacing="2" width="80%">
  <tbody><tr>
    <td><span class="genmed"><br>掲示板の管理者とモデレーターは、不適切な記事を発見次第削除/編集するように心がけますが、全ての記事に目を通すことはできません。そのため、この掲示板に投稿される全ての記事はその投稿者の視点と意見を表現するものであり、掲示板管理者、モデレーター、サイト管理者の視点と意見を表現するものではなく、管理人は記事に対する責任を一切負いません（掲示板管理者、モデレーター、サイト管理者自身の記事は除く）。<br><br>口汚い記事、猥褻な言葉、品性を欠く記事、他人を中傷する記事、嫌悪感を与える記事、脅迫的な記事、性的差別につながる記事、法律を違反する記事の投稿は禁止します。この規約を破った場合は、対象ユーザーのアカウント停止が即座に行われます（場合によっては対象ユーザーのプロバイダーに報告されます）。このような処置を実行するために、全ての記事のIPアドレスが記録されています。掲示板管理者、モデレーター、サイト管理者は、自らの判断で掲示板の如何なる記事を削除、編集、移動、ロックする権限があります。あなたが掲示板上で入力した情報をデータベースに保管されます。あなたの同意がない限り、この情報は第三者に公開されることはありませんが、ハッキング等によるデータの損傷や盗難があった場合は掲示板管理者、モデレーター、サイト管理者はその責任を一切負いません。<br><br>この掲示板では、あなたのローカル・コンピューターに情報を保管するためにCookieを使用しています。このCookieは、掲示板の使い勝手の向上させるための情報しか含まれません。メールアドレスは、登録したアカウントの詳細とパスワードを確認するためにだけ使われます（現在のパスワードを忘れた場合、パスワードを再発行する場合にも使われます）。<br /><br />

登録を続ける場合は、これらの規約に同意したものと見なされます。<br /><br /><br />

<div align="center">
<form method="POST" action="<%self%>?special=register">
<input type="hidden" name="subSilver_action" value="register_agreed" />
<input type="submit" value="私は13歳以上です。この規約に同意します。" />
</form><br />
<form method="GET" action="<%self%>">
<input type="submit" value="この規約に同意しません。" />
</form>
</div>
</span></td>

  </tr>
  </tbody></table></td>
</tr>
</tbody></table>
